stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6.3-jdk-11
  tags:
    - deploy-crypto-world-be
  script:
    - mvn clean package
    - sudo docker build -t cryptoworld/eureka-server:prod ./eureka-server/
    - sudo docker build -t cryptoworld/api-gateway:prod ./api-gateway/
    - sudo docker build -t cryptoworld/analytic-service:prod ./analytic-service/
    - sudo docker build -t cryptoworld/company-service:prod ./company-service/
    - sudo docker build -t cryptoworld/geography-service:prod ./geography-service/
    - sudo docker build -t cryptoworld/logging-service:prod ./logging-service/
    - sudo docker build -t cryptoworld/marketplace-service:prod ./marketplace-service/
    - sudo docker build -t cryptoworld/transaction-service:prod ./transaction-service/
    - sudo docker build -t cryptoworld/user-service:prod ./user-service/
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - sudo docker compose up -d
  only:
    - dev