stages:
  - build
  - deploy

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.8.4-openjdk-17
  tags:
    - deploy-crypto-world-be
  script:
    - docker-compose build
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

deploy:
  stage: deploy
  image: docker:19.03.12
  tags:
    - deploy-crypto-world-be
  script:
    - docker compose up -d
