stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/analytic-service:$CI_COMMIT_REF_SLUG analytic-service/.
    - docker push $CI_REGISTRY_IMAGE/analytic-service:$CI_COMMIT_REF_SLUG
    # Repeat the above two lines for each service
  only:
    - prod

deploy:
  stage: deploy
  script:
    - echo "Deploy script goes here"
  only:
    - prod
