
stages:
  - build
  - deploy


build:
  stage: build
  tags:
    - deploy-crypto-world-be
  image: maven:3.6.3-jdk-11
  script:
    - sudo docker-compose build 
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  tags:
    - deploy-crypto-world-be
  image: docker:19.03.12
  script:
    - sudo docker-compose up -d
