image: docker:latest

services:
  - docker:dind

stages:
  - build
  - docker-build
  - deploy

variables:
  MAVEN_OPTS: "-Xmx1024m"
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - ./mvnw package

docker-build:
  stage: docker-build
  script:
    - docker-compose build
    - docker-compose push

deploy:
  stage: deploy
  script:
    - docker-compose pull
    - docker-compose up -d
  environment:
    name: production
  when: manual
  only:
    - main