version: '3'

services:
  # Eureka Server #
  eureka-server:
    build: ./eureka-server
    ports:
      - "8010:8010"
    networks:
      - service_network
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 5


  # Transaction Service #
  transaction-service:
    build: ./transaction-service
    ports:
      - "8093:8093"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - user-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  # Company Service #
  company-service:
    build: ./company-service
    ports:
      - "8094:8094"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - user-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  # Geography Service #
  geography-service:
    build: ./geography-service
    ports:
      - "8095:8095"
    networks:
      - service_network
    depends_on:
      - eureka-server
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  # Marketplace Service #
  marketplace-service:
    build: ./marketplace-service
    ports:
      - "8096:8096"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - user-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  # User Service #
  user-service:
    build: ./user-service
    ports:
      - "8097:8097"
    networks:
      - service_network
    depends_on:
      - eureka-server
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  # Analytics Service #
  analytic-service:
    build: ./analytic-service
    ports:
      - "8098:8098"
    networks:
      - service_network
    depends_on:
      - eureka-server
      - user-service
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 5s
      timeout: 15s
      retries: 3

  # API Gateway #
  api-gateway:
    build: ./api-gateway
    ports:
      - "9090:9090"
    networks:
      - service_network
    depends_on:
      - eureka-server
    environment:
      - server.port=9090
      - spring.application.name=api-gateway-prod
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8010/eureka/
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=true
      - spring.cloud.gateway.discovery.locator.enabled=true
      - spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true

networks:
  service_network:
    driver: bridge
