version: '3.7'

services:
  eureka-server:
    image: cryptoworld/eureka-server:prod
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    image: cryptoworld/api-gateway:prod
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - "9090:9090"

  analytic-service:
    image: cryptoworld/analytic-service:prod
    container_name: analytic-service
    depends_on:
      - eureka-server
      - api-gateway

  authentication-service:
    image: cryptoworld/authentication-service:prod
    container_name: authentication-service
    depends_on:
      - eureka-server
      - api-gateway

  company-service:
    image: cryptoworld/company-service:prod
    container_name: company-service
    depends_on:
      - eureka-server
      - api-gateway

  geography-service:
    image: cryptoworld/geography-service:prod
    container_name: geography-service
    depends_on:
      - eureka-server
      - api-gateway

  logging-service:
    image: cryptoworld/logging-service:prod
    container_name: logging-service
    depends_on:
      - eureka-server
      - api-gateway

  marketplace-service:
    image: cryptoworld/marketplace-service:prod
    container_name: marketplace-service
    depends_on:
      - eureka-server
      - api-gateway

  transaction-service:
    image: cryptoworld/transaction-service:prod
    container_name: transaction-service
    depends_on:
      - eureka-server
      - api-gateway

  user-service:
    image: cryptoworld/user-service:prod
    container_name: user-service
    depends_on:
      - eureka-server
      - api-gateway
